### ISSUE TITLE
User research news sentiment

### ISSUE THREAD

**Issue by tarikeshaq** [ubclaunchpad/news-sentiment#1]
Run initial research to understand what users find valuable in the news.

## What to keep in mind
User research will keep on going throughout the weeks, our goal is to have enough to choose our next step.

In our discussion, we came up with two possible approaches for the mvp:
- A chrome extenstion that provides the sentiment of a page the user is on
- A web application that displays news from different sources and their sentiment

The work here does not have to end with either approaches, although the goal is to have a choice on what our Minimum Viable **Product** is.

## Deliverables (i.e the definition of done)
- A recommended MVP (either from the above two discussed or another - with justification)

**Comment by tarikeshaq** [comment]
Some discussion from the UI/UX workshop:
@mmanas8  and @AstridGreenh thank you for sharing the data! If you have any additional insights/comments that I missed please add them!

### Insights from survey
- **This is the most important insight** The majority of responses said they would ***not*** use an application/program that tells them the sentiment of the news. and here's some reasoning
   - People thought that the definition of positive and negative is extremely subjective in news
   - People also thought that they **want** to hear the negative news
   - People also thought that they have the capacity to decide themselves and in combination with the above two reasons have no need for a product that does this.
- Majority of news readers read news on mobile
### Some takeaways
- From a user prespective, simply classifying news into "positive" and "negative" or "good" and "bad" is **not** useful.
- We need to take a different direction, some possible directions discussed below
- We understand that users have a desire to hear both sides of the news and don't want to be ignorant
- Users have strong concerns about the bias of any product that would interact with the news

### Possible approaches
@mmanas8  and @AstridGreenh  pitched a few possible approaches we can take that align with what the users concerns are:
- We can tackle objective sentiments about the news, specifically triggers. (i.e we can show if an article contains triggering information or contrivertial topics and simply display a trigger warning) - **this is the closest to what our original idea was and the least risky**.
- We can pivot to tackle the users' desire to hear "all" the news, and instead of classifying the news, we aim to aggregate all sources of the same news article (for example we provide both the CNN and FOX articles on the SCOTUS nomination) - **this seems to be the most useful based on the user feedback**

### Some comments
The two approaches listed above seem a lot more specific that what our original idea was and probably have a easier to reach MVP. The first one is the closest to what was discussed in our conversations, and the second seems to be more useful in terms of the user.
**In our next meeting** my goal is pick an approach and dig deeper into it, the approach doesn't have to be one of the two, so **if anyone has any final approaches they want to include, please post them here as comments**

**Comment by lhao03** [comment]
I came across this, https://newslytics.io/, maybe combine it with the second possible approach of aggregating sources of same news articles? It could show what types of news you gravitate towards (CNN/Fox) and other analytics.

**Comment by tarikeshaq** [comment]
That looks very interesting, thanks for sharing @lhao03! Seems to be very similar to what we had in mind and adds this concept of presenting the *analytics* to the user... interesting will make sure to bring it into our discussion on Tuesday!

**Comment by AstridGreenh** [comment]
Here is the raw survey data is anyone is interested : [link](https://docs.google.com/forms/d/19afc8RROxHJwHIvCIo_RMWFK--6noHEXPJPIf5eAVts/edit?usp=sharing)
