### ISSUE TITLE
Implement adding articles

### ISSUE THREAD

**Issue by tarikeshaq** [ubclaunchpad/news-sentiment#34]
Depends on #32 and #16 

Implement the POST "articles/" route that adds a new article to the database

Process the request as a `json` request and send the response as a `json` response.

**Comment by tarikeshaq** [comment]
#36 Shows how you could do this, simply repeat what was done for the `user`

**Comment by lhao03** [comment]
![image](https://user-images.githubusercontent.com/55033656/98487710-d16ef480-21e1-11eb-946f-4a01236b59c4.png)
not sure what to return if added successfully. Right now it returns something like "success".

**Comment by tarikeshaq** [comment]
Success is ok! We can also return the id, we might later decide that it's better to return something else, but for now, success or the 'id' is okay. Shouldn't be too bad to add more information if needed later
